### ISSUE TITLE
Happy Hospital references itself

### ISSUE THREAD

**Issue by Niklink** [hsmusic/hsmusic-data#489]
It just does. Maybe should be an error check on the wiki code side to check self references/samples?

Thanks, mehbark!

**Comment by towerofnix** [comment]
not certain on wiki-side error—if we allow [directed cycles](https://en.wikipedia.org/wiki/Cycle_graph#Directed_cycle_graph) (i.e. circles/loops: A refs B, B refs A; [#hsmusic-chat](https://discord.com/channels/749042497610842152/779895315750715422/1060160882858008657)), then constraint "no self-referencing" feels inconsistently specialized. better to locate via occasional check in REPL:

```
> trackData.filter(t => t.referencedTracks.includes(t))
[
  Track "Happy Hospital" (track:happy-hospital) (#40 in Call and New V)
]
```

mandating acyclic graph via `wiki-info.yaml` flag would be OK & useful for other wikis (or even as default)—but likely inappropriate for hsmusic-data. could similarly have flag for self-references, allow wikis to customize as desired

```yaml
# we'd do this in hsmusic-data
# since we don't exactly "prescribe" the meaning of refs
# at the scale of this dataset
Allow Tracks Referencing Selves: true
Allow Tracks Referencing Cycles: true

# if unspecified (e.g. new wikis)
# then you'd get errors as crop-up
```
